# Generated by Django 6.0.2 on 2026-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='childhood',
            field=models.CharField(blank=True, null=True),
        ),
    ]
