# Generated by Django 6.0.2 on 2026-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_celebrity_childhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='biograghy',
        ),
        migrations.AddField(
            model_name='celebrity',
            name='biography',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
