# Generated by Django 6.0.2 on 2026-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_remove_celebrity_biograghy_celebrity_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
