# Generated by Django 6.0.2 on 2026-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_celebrity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(null=True, upload_to='celebrity_image'),
        ),
    ]
