# Generated by Django 6.0.2 on 2026-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0006_category_celebrity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='celebrity_image'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='professions',
            field=models.ManyToManyField(to='celebrities.professions'),
        ),
    ]
